set_property PACKAGE_PIN E3 [get_ports clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_0]
set_property PACKAGE_PIN M20 [get_ports reset_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_0]
set_property PACKAGE_PIN R14 [get_ports {next_state_0[1]}]
set_property PACKAGE_PIN V9 [get_ports {next_state_0[0]}]
set_property PACKAGE_PIN R2 [get_ports {state_0[1]}]
set_property PACKAGE_PIN P2 [get_ports {state_0[0]}]
set_property PACKAGE_PIN D20 [get_ports w_0]
set_property PACKAGE_PIN G17 [get_ports z_0]
set_property IOSTANDARD LVCMOS33 [get_ports w_0]
set_property IOSTANDARD LVCMOS33 [get_ports z_0]
set_property IOSTANDARD LVCMOS33 [get_ports {state_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {next_state_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {next_state_0[0]}]

